# Generated by Django 3.0 on 2020-06-13 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_comment',
        ),
    ]
