# Generated by Django 2.2 on 2020-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='is_friend',
            field=models.BooleanField(default=False, verbose_name='Is a friend?'),
        ),
    ]
