# Generated by Django 3.0 on 2020-06-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200605_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerRelation',
        ),
    ]
