# Generated by Django 3.0 on 2020-06-05 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_delete_followerrelation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='following',
            new_name='followers',
        ),
    ]
