# Generated by Django 3.0 on 2020-06-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20200607_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='is_friend',
        ),
    ]
